FROM node:20-alpine

WORKDIR /app

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG SUPABASE_URL
ARG SUPABASE_SERVICE_ROLE_KEY
ARG NAVER_CLIENT_ID
ARG NAVER_CLIENT_SECRET
ARG BASE_URL
ARG PORT

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV NAVER_CLIENT_ID=$NAVER_CLIENT_ID
ENV NAVER_CLIENT_SECRET=$NAVER_CLIENT_SECRET
ENV BASE_URL=$BASE_URL
ENV PORT=$PORT

COPY package.json ./
COPY frontend ./frontend
COPY backend ./backend

RUN npm run build

EXPOSE 3001

CMD ["npm", "start"]
