FROM node:20-alpine

WORKDIR /app

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY

COPY package.json ./
COPY frontend ./frontend
COPY backend ./backend

RUN npm run build

EXPOSE 3001

CMD ["npm", "start"]
